const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  title: state => state.settings.title,
  backEndBaseUrl: state => state.settings.backEndBaseUrl,
  searchByRela: state => state.entity.searchByRela,
  powerSupplyCompany: state => state.entity.powerSupplyCompany,
  powerSupplyAdmin: state => state.entity.powerSupplyAdmin,
  center: state => state.entity.center,
  radius: state => state.entity.radius,
  bounds: state => state.entity.bounds,
  deviceTypes: state => state.dict.deviceTypes,
  useEnvs: state => state.dict.useEnvs,
  deptMap: state => state.dict.deptMap,
  childDeptMap: state => state.dict.childDeptMap,
}
export default getters
